export enum GovijanaSewaCategory {
  GENERAL = 'GENERAL',
  FERTILIZER = 'FERTILIZER',
  SEED_DISTRIBUTION = 'SEED_DISTRIBUTION',
  FINANCIAL_SUPPORT = 'FINANCIAL_SUPPORT',
  ADVISORY = 'ADVISORY',
  OTHER = 'OTHER',
}
