export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  FARMER = "FARMER",
  AGRICULTURE_ADVISOR = "AGRICULTURE_ADVISOR",
  IRRIGATION_OFFICER = "IRRIGATION_OFFICER",
  SUPERVISOR = "SUPERVISOR",
  ORGANIZATION_MANAGER = "ORGANIZATION_MANAGER",
}